language: objective-c
before_install:
    - rvm install 2.3.0
    - gem install cocoapods --pre
    - pod repo update
script: cd XWalkView; pod install; xcodebuild -workspace XWalkView.xcworkspace -scheme XWalkViewTests -configuration Debug -destination 'platform=iOS simulator,name=iPhone 6' test
